apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alice
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: ssh://git@git.default.svc.cluster.local:bortrand
    targetRevision: stable
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
